/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_paile_cvcamera_CvProcess */

#ifndef _Included_com_paile_cvcamera_CvProcess
#define _Included_com_paile_cvcamera_CvProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_paile_cvcamera_CvProcess
 * Method:    processImage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_paile_cvcamera_CvProcess_processImage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
